.TH R-circuits 1 "R-áramkör számító alkalmazás" "Pozsár Zsolt" "R-áramkör számító alkalmazás"
.SH NÉV
R-circuits \- R-áramkör számító alkalmazás
.SH ÁTTEKINTÉS
.B r-circuits [-h | --help | -o | -offline | -v | --version]
.SH LEÍRÁS
Méretező alkalmazás R-áramkörökhöz,
FreeBSD, Linux és Windows operációs rendszerekre.
.PP
Nyelvi támogatás: angol és magyar.
.TE
.SH OPCIÓK
.TP
.B \-h \-\-help
Kiírja a használható paramétereket.
.TP
.B \-o \-\-offline
Off-line működési módba kapcsol.
.TP
.B \-v \-\-version
Kiírja a verzió és fordítási információkat a konzolra.
.TE
.SH SEGÍTSÉG RENDSZER
HTML állományokból felépített on-line segítséggel rendelkezik.
.PP
Az alkalmazás a segítség oldalak megjelenítésére külső megjelenítő alkalmazást
használ (web böngésző).
.SH KILÉPÉSI ÁLLAPOT
.TP
.B 0
Szabályos futás és kilépés.
.TP
.B >0
A futás során hiba lépett fel.
.SH VERZIÓ
Ez az alkalmazás 0.4.1 változata.
.SH SZERZŐ
.B Az Elektroncsövek
-et készítette Pozsár Zsolt.
.TS
tab (#);
l l.
\fBHonlap:\fR#http://www.pozsarzs.hu/
\fBE-mail:\fR#pozsarzs\@gmail.com
.TE
.TP
Copyright (c) 2011-2016 Pozsár Zsolt
