.TH r-circuits 1 "R-circuit calculator" "Pozsar Zsolt" "R-circuit calculator"
.SH NAME
R-circuits \- R-circuit calculator application
.SH SYNOPSIS
.B r-circuits [-h | --help | -o | -offline | -v | --version]
.SH DESCRIPTION
This software  is a R-circuit calculator application.
  OS support: FreeBSD, Linux and Windows.
.PP
Language support: English and Hungarian.
.TE
.SH OPTIONS
.TP
.B \-h \-\-help
Write useable parameters.
.TP
.B \-o \-\-offline
Switch to off-line operation mode.
.TP
.B \-v \-\-version
Write version and build information.
.SH HELP SYSTEM
Online help information is provided as a set of HTML text files.
.PP
This programme uses external application (web browser) to display help.
.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B >0
An error has occurred.
.SH VERSION
This applications version is 0.4.1
.SH AUTHOR
.B Electrontubes
is produced by Pozsar Zsolt.
.TS
tab (#);
l l.
\fBHomepage:\fR#http://www.pozsarzs.hu/en/
\fBE-mail:\fR#pozsarzs\@gmail.com
.TE
.TP
Copyright (c) 2011-2016 Pozsar Zsolt
